### PR TITLE
add function count

### PR DESCRIPTION
**Pull request by tborychowski**
`lineNumber` should probably be `lineCount` (number suggests an ordinal, e.g. third line)

### CODE REVIEW

**Comment by slyg** [comment]
Thanks @tborychowski the tests do not pass however I'd be happy to merge your pr.

**Comment by tborychowski** [comment]
I will fix them later, thanks :-)

**Comment by tborychowski** [comment]
Would you be able to publish that, when it's merged?
Also, as this is a breaking change (and not backwards compatible), this would probably need to be bumped to a v2.x.x

**Comment by slyg** [comment]
OK it's published, thx !

**Pull request merged**
